permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: yyf
  email: yeyafei@hotmail.com
  link: https://yeyafei.github.io/
  weibo: http://weibo.com/kill819
  github: https://github.com/yeyafei
 # music: 
 # linkedin: 

# 站点信息
title: 叶亚飞的博客
description: yyf's personal blog
url: https://yeyafei.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/yyf.png
favicon: /public/img/yyf.png

# google analytics 设置
ga:
  id: UA-54262064-1yyf 
  url: https://yeyafei.github.io/

# disqus 设置 -->换成了多说
disqus:
  shortname: yyfblog

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
#cates: 
 # - Optimization
 # - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
